name: quality_monitor
channels:
  - conda-forge
  - azureml
dependencies:
  - python=3.11.11
  - jupyterlab=4.4.0
  - pandas=2.2.3
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - numpy=2.0.1
  - plotly=6.0.1
  - itables=2.3.0
  - streamlit=1.32.0
  - openpyxl=3.1.2
  - azureml-core
  - azureml-dataset-runtime
  - azureml-defaults
  - azureml-mlflow
